### PR TITLE
warn when mixed in property is shadowing a property on base type

### LINKED ISSUE #95: Warn when a component property shadows a DOM Element property
I ran into an issue with a component defining a [tagName](https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName) property like this:

```js
class MyComponent extends StacheElement {
  static get view() {
    return "";
  }

  static get props() {
    return {
      tagName: String
    };
  }
}
```

can-stache-bindings throws the following error:

```
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.viewModel 
    at makeDataBinding
```

There is a warning already in place when components define an `error` property. We should extend that functionality.

### PR DESCRIPTION
**Pull request by nlundquist**
Resolves #95

### CODE REVIEW

File: src/mixin-props.js [hunk 1]
```diff
@@ -22,28 +22,37 @@ module.exports = function mixinDefine(Base = HTMLElement) {
...
 				Type.props :
 				typeof Type.define === "object" ?
 					Type.define :
 					{};
+			
 			Object.keys(props).forEach(function(key) {
 				if("on" + key in Type.prototype) {
 					canLogDev.warn(`${canReflect.getName(Type)}: The defined property [${key}] matches the name of a DOM event. This property could update unexpectedly. Consider renaming.`);
 				}
+				else if(key in Base.prototype) {
```
Comment (nlundquist) [inline src/mixin-props.js:42]: Should this check be constrained so it only applies when `Base` is a built-in type? If so, how could this be done?

**Comment by nlundquist** [comment]
It's also worth noting that with the addition of this change a warning is now produced by this and similar components used during testing:

https://github.com/canjs/can-stache-element/blob/e2f328becda17d1980ef3a6bf15467997a4afcaa/src/mixin-bindings-test.js#L97-L109

This is of course since the `id` property is already present on HTMLElement. None of these warnings prevent tests from proceeding as normal.

File: src/mixin-props.js (hunk 1 above)
Comment (phillipskevin) [reply src/mixin-props.js:42]: I think this check is safe for now.

**Review by phillipskevin — APPROVED** [review]
